package brightspark.trelloembedbot

import net.dv8tion.jda.core.EmbedBuilder
import net.dv8tion.jda.core.entities.Guild
import net.dv8tion.jda.core.entities.MessageChannel
import java.awt.Color

object Utils {
    const val trelloKey: String = "10a61e7cd59f0840e292b285a9b21dab"

    private val dmMessage = """
            |Hey there, to manage the Trello token for your server **%s**, please have a read below.
            |
            |Trello tokens are generated by a Trello user and is tied to their account, and I use that to access info about any cards or boards posted in Discord.
            |**Note:** I can only access boards that the token's Trello user can access!
            |
            |To generate a token, please click this link and allow access for this bot:
            |<https://trello.com/1/authorize?expiration=never&name=Trello+Embedder&scope=read&response_type=token&key=$trelloKey>
            |Now that you have your token, you need to tell me about it!
            |
            |To set the token, please use:
            |`set <token>`
            |
            |To check the token set for your server, use:
            |`get`
            |
            |If you want to remove the token for your server, use:
            |`del`
            |
            |And that's it! While a token is set, I will respond to board and card links in channels I have access to with info about them :)
            |
            |The ability to use commands here will expire after 5 minutes.
            |If you want to end it early, use:
            |`end`
            """.trimMargin()

    fun getDmMessage(guild: Guild): String = String.format(dmMessage, guild.name)

    fun sendMessage(channel: MessageChannel, desc: String, title: String? = null, success: Boolean = true) {
        val builder = EmbedBuilder()
                .setDescription(desc)
                .setColor(if (success) Color.GREEN else Color.RED)
        title?.let { builder.setTitle(it) }
        channel.sendMessage(builder.build()).queue()
    }
}